
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN DIVIDE ID INT LPAREN MINUS NUMBER PLUS RPAREN SEMI TIMESprogram : program statement\n| statementstatement : INT ID SEMIstatement : INT ID ASSIGN expression SEMIstatement : ID ASSIGN expression SEMIexpression : expression PLUS termexpression : termterm : term TIMES factorterm : factorfactor : NUMBERfactor : ID'
    
_lr_action_items = {'INT':([0,1,2,5,8,16,19,],[3,3,-2,-1,-3,-5,-4,]),'ID':([0,1,2,3,5,7,8,9,16,17,18,19,],[4,4,-2,6,-1,10,-3,10,-5,10,10,-4,]),'$end':([1,2,5,8,16,19,],[0,-2,-1,-3,-5,-4,]),'ASSIGN':([4,6,],[7,9,]),'SEMI':([6,10,11,12,13,14,15,20,21,],[8,-11,16,-7,-9,-10,19,-6,-8,]),'NUMBER':([7,9,17,18,],[14,14,14,14,]),'TIMES':([10,12,13,14,20,21,],[-11,18,-9,-10,18,-8,]),'PLUS':([10,11,12,13,14,15,20,21,],[-11,17,-7,-9,-10,17,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,1,],[2,5,]),'expression':([7,9,],[11,15,]),'term':([7,9,17,],[12,12,20,]),'factor':([7,9,17,18,],[13,13,13,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program statement','program',2,'p_program','parser.py',15),
  ('program -> statement','program',1,'p_program','parser.py',16),
  ('statement -> INT ID SEMI','statement',3,'p_statement_decl','parser.py',22),
  ('statement -> INT ID ASSIGN expression SEMI','statement',5,'p_statement_decl_assign','parser.py',26),
  ('statement -> ID ASSIGN expression SEMI','statement',4,'p_statement_assign','parser.py',31),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',37),
  ('expression -> term','expression',1,'p_expression_term','parser.py',43),
  ('term -> term TIMES factor','term',3,'p_term_times','parser.py',47),
  ('term -> factor','term',1,'p_term_factor','parser.py',53),
  ('factor -> NUMBER','factor',1,'p_factor_number','parser.py',57),
  ('factor -> ID','factor',1,'p_factor_id','parser.py',61),
]
